language: cpp
compiler:
    - clang
    - gcc
notifications:
    email: false
jobs:
    include:
        - script: make test
          name: "Run unit tests"
        - script: make examples
          name: "Run examples"
        - script: make check-format
          name: "Check formatting"
        - stage: deploy
          name: "Deploy documentation"
          script: skip
          deploy:
            provider: pages
            skip-cleanup: true
            github-token: $GITHUB_TOKEN
            keep-history: true
            on:
              branch: master
