language: cpp

compiler:
- clang
- gcc
env:
- JOB_TYPE=test
- JOB_TYPE=examples
script: make $JOB_TYPE
jobs:
    include:
    - script: make check-format
      name: "Check Formatting"
    - stage: deploy
      if: type = push AND branch = master
      before_script: sudo apt-get install -y doxygen doxygen-doc doxygen-latex doxygen-gui graphviz
      script: make docs
      name: "Deploy Documentation"
      deploy:
        provider: pages
        local-dir: docs/
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        on:
          branch: master
notifications:
    email: false
