language: cpp

compiler:
  - clang
  - gcc
env:
  - JOB_TYPE=test
  - JOB_TYPE=examples
script: make $JOB_TYPE
jobs:
  include:
    - script: make check-format
      name: "Check Formatting"
    - stage: deploy
      if: type = push AND branch = master
      addons:
        apt:
          packages:
            - doxygen
            - doxygen-latex
            - graphviz
      script:
        - cmake -H. -Bbuild
        - cmake --build build --clean-first --target docs
      name: "Deploy Documentation"
      deploy:
        provider: pages
        local-dir: build/html/
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        on:
          branch: master
notifications:
  email: false
