language: cpp

compiler:
- clang
- gcc
env:
- JOB_TYPE=test
- JOB_TYPE=examples
script: make $JOB_TYPE
before_deploy: sudo apt-get install -y doxygen doxygen-doc doxygen-latex doxygen-gui graphviz
jobs:
    include:
    - script: make check-format
      name: "Check formatting"
    - stage: deploy
      name: "Deploy documentation"
      script: make docs
      deploy:
        provider: pages
        local-dir: docs/
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        on:
          branch: master
notifications:
    email: false
